name: Build and Upload Artifacts
on:
  push:
    branches: ["kdc2024"]
  pull_request:
    branches: ["kdc2024"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x (This is the last major version that pkg supports)
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Download dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
      # run: npm test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kdc-overlay
          path: dist/kdc-overlay.exe
