# Overlay Server Port
port: 3000

# Log Level
# error: 0, warn: 1, info: 2, http: 3, verbose: 4, debug: 5, silly: 6
logLevel: 2

# Stream Data Sheet
sheet: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# osu!api v2
clientID: 0
clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Gosumemory
gosumemoryHost: "127.0.0.1"
gosumemoryPort: 24050

# foobar2000
fb2k:
  beefweb:
    host: "127.0.0.1"
    port: 8880
  controlserver:
    host: "127.0.0.1"
    port: 3333
